### PR TITLE
Translate syllabus and sample exam documents

### PR DESCRIPTION
**Pull request by Witiko**
Closes https://github.com/istqborg/istqb_product_base/issues/122.

### CODE REVIEW

**Comment by Witiko** [comment]
Below, I show how the documents `sample-exam-questions.tex` and `sample-exam-questions.tex` from the repository `istqb_product_template` look after this PR with the following changes to change the documents to German:

``` diff
diff --git a/sample-exam-answers.tex b/sample-exam-answers.tex
index b765637..14f3bc7 100644
--- a/sample-exam-answers.tex
+++ b/sample-exam-answers.tex
@@ -25,9 +25,9 @@
 
 % Document Text
 \istqblandscapebegin
-\istqbunnumberedsection{Answer Key}
+\istqbunnumberedsection{Lösungsschlüssel}
 \markdownInput[snippet=answer-key]{sample-exam-answers/questions.yml}
-\istqbunnumberedsection{Answers}
+\istqbunnumberedsection{Antworten}
 \markdownInput[snippet=answers]{sample-exam-answers/questions.yml}
 \istqblandscapeend
 
diff --git a/sample-exam-questions.tex b/sample-exam-questions.tex
index 064064c..2abcb92 100644
--- a/sample-exam-questions.tex
+++ b/sample-exam-questions.tex
@@ -24,7 +24,7 @@
 \istqbtableofcontents
 
 % Document Text
-\istqbunnumberedsection{Questions}
+\istqbunnumberedsection{Fragen}
 \markdownInput[snippet=questions]{sample-exam-questions/questions.yml}
 
 \end{document}
diff --git a/sample-exam/metadata.yml b/sample-exam/metadata.yml
index c10362e..f631c0b 100644
--- a/sample-exam/metadata.yml
+++ b/sample-exam/metadata.yml
@@ -3,9 +3,10 @@ level: Foundation Level
 title: Syllabus Template
 code: CT-TEMP
 prefix: TEMP
-type: Sample Exam
+type: Probeprüfung
 version: v0.1
 compatibility: Compatible with Syllabus v0.1
 date: YYYY/MM/DD
 release: For internal use only
 logo: istqb-logo-default
+language: de
diff --git a/sample-exam/questions.md b/sample-exam/questions.md
index cf1dcb9..74676a5 100644
--- a/sample-exam/questions.md
+++ b/sample-exam/questions.md
@@ -24,7 +24,7 @@ d. Is not correct. It is impossible to test all combinations of inputs (see test
 # metadata
 lo: 1.4.2
 k-level: K2
-points: 1
+points: 2
 correct: b
 
 ## question
```

### Sample Exam Questions
#### Landing page
image
#### Table of contents
image
#### Questions
image
image

### Sample Exam Answers
#### Landing page
image
#### Table of contents
image
#### Answer key
image
#### Answers
image
image

**Comment by Witiko** [comment]
Below, I show how the documents `sample-exam-questions.tex` and `sample-exam-questions.tex` from the repository `istqb_product_template` look after this PR with the following changes to change the documents to Czech:

``` diff
diff --git a/sample-exam-answers.tex b/sample-exam-answers.tex
index b765637..14f3bc7 100644
--- a/sample-exam-answers.tex
+++ b/sample-exam-answers.tex
@@ -25,9 +25,9 @@
 
 % Document Text
 \istqblandscapebegin
-\istqbunnumberedsection{Answer Key}
+\istqbunnumberedsection{Klíč k odpovědím}
 \markdownInput[snippet=answer-key]{sample-exam-answers/questions.yml}
-\istqbunnumberedsection{Answers}
+\istqbunnumberedsection{Odpovědi}
 \markdownInput[snippet=answers]{sample-exam-answers/questions.yml}
 \istqblandscapeend
 
diff --git a/sample-exam-questions.tex b/sample-exam-questions.tex
index 064064c..2abcb92 100644
--- a/sample-exam-questions.tex
+++ b/sample-exam-questions.tex
@@ -24,7 +24,7 @@
 \istqbtableofcontents
 
 % Document Text
-\istqbunnumberedsection{Questions}
+\istqbunnumberedsection{Otázky}
 \markdownInput[snippet=questions]{sample-exam-questions/questions.yml}
 
 \end{document}
diff --git a/sample-exam/metadata.yml b/sample-exam/metadata.yml
index c10362e..f631c0b 100644
--- a/sample-exam/metadata.yml
+++ b/sample-exam/metadata.yml
@@ -3,9 +3,10 @@ level: Foundation Level
 title: Syllabus Template
 code: CT-TEMP
 prefix: TEMP
-type: Sample Exam
+type: Ukázkový test
 version: v0.1
 compatibility: Compatible with Syllabus v0.1
 date: YYYY/MM/DD
 release: For internal use only
 logo: istqb-logo-default
+language: cs
diff --git a/sample-exam/questions.md b/sample-exam/questions.md
index cf1dcb9..74676a5 100644
--- a/sample-exam/questions.md
+++ b/sample-exam/questions.md
@@ -24,7 +24,7 @@ d. Is not correct. It is impossible to test all combinations of inputs (see test
 # metadata
 lo: 1.4.2
 k-level: K2
-points: 1
+points: 2
 correct: b
 
 ## question
```

### Sample Exam Questions
#### Landing page
image
#### Table of contents
image
#### Questions
image
image

### Sample Exam Answers
#### Landing page
image
#### Table of contents
image
#### Answer key
image
#### Answers
image
image

Can you suggest a better Czech translation for the text "K-Level"?

**Comment by Witiko** [comment]
Below, I show how the documents `sample-exam-questions.tex` and `sample-exam-questions.tex` from the repository `istqb_product_template` look after this PR with the following changes to change the documents to Slovak:

``` diff
diff --git a/sample-exam-answers.tex b/sample-exam-answers.tex
index b765637..14f3bc7 100644
--- a/sample-exam-answers.tex
+++ b/sample-exam-answers.tex
@@ -25,9 +25,9 @@
 
 % Document Text
 \istqblandscapebegin
-\istqbunnumberedsection{Answer Key}
+\istqbunnumberedsection{Kľúč k odpovediam}
 \markdownInput[snippet=answer-key]{sample-exam-answers/questions.yml}
-\istqbunnumberedsection{Answers}
+\istqbunnumberedsection{Odpovede}
 \markdownInput[snippet=answers]{sample-exam-answers/questions.yml}
 \istqblandscapeend
 
diff --git a/sample-exam-questions.tex b/sample-exam-questions.tex
index 064064c..2abcb92 100644
--- a/sample-exam-questions.tex
+++ b/sample-exam-questions.tex
@@ -24,7 +24,7 @@
 \istqbtableofcontents
 
 % Document Text
-\istqbunnumberedsection{Questions}
+\istqbunnumberedsection{Otázky}
 \markdownInput[snippet=questions]{sample-exam-questions/questions.yml}
 
 \end{document}
diff --git a/sample-exam/metadata.yml b/sample-exam/metadata.yml
index c10362e..f631c0b 100644
--- a/sample-exam/metadata.yml
+++ b/sample-exam/metadata.yml
@@ -3,9 +3,10 @@ level: Foundation Level
 title: Syllabus Template
 code: CT-TEMP
 prefix: TEMP
-type: Sample Exam
+type: Ukážkový test
 version: v0.1
 compatibility: Compatible with Syllabus v0.1
 date: YYYY/MM/DD
 release: For internal use only
 logo: istqb-logo-default
+language: sk
diff --git a/sample-exam/questions.md b/sample-exam/questions.md
index cf1dcb9..74676a5 100644
--- a/sample-exam/questions.md
+++ b/sample-exam/questions.md
@@ -24,7 +24,7 @@ d. Is not correct. It is impossible to test all combinations of inputs (see test
 # metadata
 lo: 1.4.2
 k-level: K2
-points: 1
+points: 2
 correct: b
 
 ## question
```

### Sample Exam Questions
#### Landing page
image
#### Table of contents
image
#### Questions
image
image

### Sample Exam Answers
#### Landing page
image
#### Table of contents
image
#### Answer key
image
#### Answers
image
image

Can you suggest a better Slovak translation for the text "K-Level"?

**Comment by danopolan** [comment]
I am OK with the changes.

@JaGi-GTB can you please have a look on German version as well?
If you want to test it on TAS or TAE syllabus, just update [.github/workflows/compile.yml, line 15](https://github.com/istqborg/istqb-ct-tas/blob/Beta-Review-Findings/.github/workflows/compile.yml#L15) to `uses: istqborg/istqb_product_base/.github/workflows/compile.yml@feat/syllabus-and-exam-documents-general-text-translations`

**Comment by Witiko** [comment]
> If you want to test it on TAS or TAE syllabus, just update [.github/workflows/compile.yml, line 15](https://github.com/istqborg/istqb-ct-tas/blob/Beta-Review-Findings/.github/workflows/compile.yml#L15) to `uses: istqborg/istqb_product_base/.github/workflows/compile.yml@feat/syllabus-and-exam-documents-general-text-translations`

Rather, you should set line 19 to `base-version: feat/syllabus-and-exam-documents-general-text-translations` to use the code from this PR in your workflow. Changing `uses:` only changes the workflow definitions and would have no effect here, since we made no changes to these definitions in this PR.

**Review by danopolan — APPROVED** [review]
We can merge this one

**Pull request merged**
